version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: taura-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taura
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8080"

volumes:
  pg_data:
